controller_server:
  ros__parameters:
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      critics:
        - RotateToGoalCritic
        - PathAlignCritic
        - GoalAlignCritic
        - OscillationCritic
        - ObstacleFootprintCritic
        - GoalCritic
      min_vel_x: 0.0
      max_vel_x: 0.26
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 1.82
      min_speed_xy: 0.0
      max_speed_xy: 0.26
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.1
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true
      short_circuit_trajectory_evaluation: true
      publish_evaluation: true
      publish_global_plan: true
      debug_trajectory_details: true
      use_differential_drive: true
      use_angular_velocity: true
      use_velocity_scaled_lookahead: false
      use_velocity_scaled_lookahead_and_granularity: false
      use_velocity_scaled_sim_time: false
      use_velocity_scaled_samples: false
      use_velocity_scaled_acc_lim: false
      use_velocity_scaled_decel_lim: false
      use_velocity_scaled_max_vel: false
      use_velocity_scaled_min_vel: false
      use_velocity_scaled_max_speed_xy: false
      use_velocity_scaled_min_speed_xy: false
      use_velocity_scaled_max_vel_theta: false
      use_velocity_scaled_min_vel_theta: false
      use_velocity_scaled_acc_lim_theta: false
      use_velocity_scaled_decel_lim_theta: false
      use_velocity_scaled_max_speed_theta: false
      use_velocity_scaled_min_speed_theta: false
      use_velocity_scaled_max_vel_x: false
      use_velocity_scaled_min_vel_x: false
      use_velocity_scaled_acc_lim_x: false
      use_velocity_scaled_decel_lim_x: false
      use_velocity_scaled_max_speed_x: false
      use_velocity_scaled_min_speed_x: false
      use_velocity_scaled_max_vel_y: false
      use_velocity_scaled_min_vel_y: false
      use_velocity_scaled_acc_lim_y: false
      use_velocity_scaled_decel_lim_y: false
      use_velocity_scaled_max_speed_y: false
      use_velocity_scaled_min_speed_y: false
      use_velocity_scaled_max_vel_z: false
      use_velocity_scaled_min_vel_z: false
      use_velocity_scaled_acc_lim_z: false
      use_velocity_scaled_decel_lim_z: false
      use_velocity_scaled_max_speed_z: false
      use_velocity_scaled_min_speed_z: false
      use_velocity_scaled_max_vel_w: false
      use_velocity_scaled_min_vel_w: false
      use_velocity_scaled_acc_lim_w: false
      use_velocity_scaled_decel_lim_w: false
      use_velocity_scaled_max_speed_w: false
      use_velocity_scaled_min_speed_w: false
      use_velocity_scaled_max_vel_v: false
      use_velocity_scaled_min_vel_v: false
      use_velocity_scaled_acc_lim_v: false
      use_velocity_scaled_decel_lim_v: false
      use_velocity_scaled_max_speed_v: false
      use_velocity_scaled_min_speed_v: false
      use_velocity_scaled_max_vel_u: false
      use_velocity_scaled_min_vel_u: false
      use_velocity_scaled_acc_lim_u: false
      use_velocity_scaled_decel_lim_u: false
      use_velocity_scaled_max_speed_u: false
      use_velocity_scaled_min_speed_u: false
      use_velocity_scaled_max_vel_t: false
      use_velocity_scaled_min_vel_t: false
      use_velocity_scaled_acc_lim_t: false
      use_velocity_scaled_decel_lim_t: false
      use_velocity_scaled_max_speed_t: false
      use_velocity_scaled_min_speed_t: false
      use_velocity_scaled_max_vel_s: false
      use_velocity_scaled_min_vel_s: false
      use_velocity_scaled_acc_lim_s: false
      use_velocity_scaled_decel_lim_s: false
      use_velocity_scaled_max_speed_s: false
      use_velocity_scaled_min_speed_s: false
      use_velocity_scaled_max_vel_r: false
      use_velocity_scaled_min_vel_r: false
      use_velocity_scaled_acc_lim_r: false
      use_velocity_scaled_decel_lim_r: false
      use_velocity_scaled_max_speed_r: false
      use_velocity_scaled_min_speed_r: false
      use_velocity_scaled_max_vel_q: false
      use_velocity_scaled_min_vel_q: false
      use_velocity_scaled_acc_lim_q: false
      use_velocity_scaled_decel_lim_q: false
      use_velocity_scaled_max_speed_q: false
      use_velocity_scaled_min_speed_q: false
      use_velocity_scaled_max_vel_p: false
      use_velocity_scaled_min_vel_p: false
      use_velocity_scaled_acc_lim_p: false
      use_velocity_scaled_decel_lim_p: false
      use_velocity_scaled_max_speed_p: false
      use_velocity_scaled_min_speed_p: false
      use_velocity_scaled_max_vel_o: false
      use_velocity_scaled_min_vel_o: false
      use_velocity_scaled_acc_lim_o: false
      use_velocity_scaled_decel_lim_o: false
      use_velocity_scaled_max_speed_o: false
      use_velocity_scaled_min_speed_o: false
      use_velocity_scaled_max_vel_n: false
      use_velocity_scaled_min_vel_n: false
      use_velocity_scaled_acc_lim_n: false
      use_velocity_scaled_decel_lim_n: false
      use_velocity_scaled_max_speed_n: false
      use_velocity_scaled_min_speed_n: false
      use_velocity_scaled_max_vel_m: false
      use_velocity_scaled_min_vel_m: false
      use_velocity_scaled_acc_lim_m: false
      use_velocity_scaled_decel_lim_m: false
      use_velocity_scaled_max_speed_m: false
      use_velocity_scaled_min_speed_m: false
      use_velocity_scaled_max_vel_l: false
      use_velocity_scaled_min_vel_l: false
      use_velocity_scaled_acc_lim_l: false
      use_velocity_scaled_decel_lim_l: false
      use_velocity_scaled_max_speed_l: false
      use_velocity_scaled_min_speed_l: false
      use_velocity_scaled_max_vel_k: false
      use_velocity_scaled_min_vel_k: false
      use_velocity_scaled_acc_lim_k: false
      use_velocity_scaled_decel_lim_k: false
      use_velocity_scaled_max_speed_k: false
      use_velocity_scaled_min_speed_k: false
      use_velocity_scaled_max_vel_j: false
      use_velocity_scaled_min_vel_j: false
      use_velocity_scaled_acc_lim_j: false
      use_velocity_scaled_decel_lim_j: false
      use_velocity_scaled_max_speed_j: false
      use_velocity_scaled_min_speed_j: false
      use_velocity_scaled_max_vel_i: false
      use_velocity_scaled_min_vel_i: false
      use_velocity_scaled_acc_lim_i: false
      use_velocity_scaled_decel_lim_i: false
      use_velocity_scaled_max_speed_i: false
      use_velocity_scaled_min_speed_i: false
      use_velocity_scaled_max_vel_h: false
      use_velocity_scaled_min_vel_h: false
      use_velocity_scaled_acc_lim_h: false
      use_velocity_scaled_decel_lim_h: false
      use_velocity_scaled_max_speed_h: false
      use_velocity_scaled_min_speed_h: false
      use_velocity_scaled_max_vel_g: false
      use_velocity_scaled_min_vel_g: false
      use_velocity_scaled_acc_lim_g: false
      use_velocity_scaled_decel_lim_g: false
      use_velocity_scaled_max_speed_g: false
      use_velocity_scaled_min_speed_g: false
      use_velocity_scaled_max_vel_f: false
      use_velocity_scaled_min_vel_f: false
      use_velocity_scaled_acc_lim_f: false
      use_velocity_scaled_decel_lim_f: false
      use_velocity_scaled_max_speed_f: false
      use_velocity_scaled_min_speed_f: false
      use_velocity_scaled_max_vel_e: false
      use_velocity_scaled_min_vel_e: false
      use_velocity_scaled_acc_lim_e: false
      use_velocity_scaled_decel_lim_e: false
      use_velocity_scaled_max_speed_e: false
      use_velocity_scaled_min_speed_e: false
      use_velocity_scaled_max_vel_d: false
      use_velocity_scaled_min_vel_d: false
      use_velocity_scaled_acc_lim_d: false
      use_velocity_scaled_decel_lim_d: false
      use_velocity_scaled_max_speed_d: false
      use_velocity_scaled_min_speed_d: false
      use_velocity_scaled_max_vel_c: false
      use_velocity_scaled_min_vel_c: false
      use_velocity_scaled_acc_lim_c: false
      use_velocity_scaled_decel_lim_c: false
      use_velocity_scaled_max_speed_c: false
      use_velocity_scaled_min_speed_c: false
      use_velocity_scaled_max_vel_b: false
      use_velocity_scaled_min_vel_b: false
      use_velocity_scaled_acc_lim_b: false
      use_velocity_scaled_decel_lim_b: false
      use_velocity_scaled_max_speed_b: false
      use_velocity_scaled_min_speed_b: false
      use_velocity_scaled_max_vel_a: false
      use_velocity_scaled_min_vel_a: false
      use_velocity_scaled_acc_lim_a: false
      use_velocity_scaled_decel_lim_a: false
      use_velocity_scaled_max_speed_a: false
      use_velocity_scaled_min_speed_a: false
      use_velocity_scaled_max_vel_z: false
      use_velocity_scaled_min_vel_z: false
      use_velocity_scaled_acc_lim_z: false
      use_velocity_scaled_decel_lim_z: false
      use_velocity_scaled_max_speed_z: false
      use_velocity_scaled_min_speed_z: false
      use_velocity_scaled_max_vel_y: false
      use_velocity_scaled_min_vel_y: false
      use_velocity_scaled_acc_lim_y: false
      use_velocity_scaled_decel_lim_y: false
      use_velocity_scaled_max_speed_y: false
      use_velocity_scaled_min_speed_y: false
      use_velocity_scaled_max_vel_x: false
      use_velocity_scaled_min_vel_x: false
      use_velocity_scaled_acc_lim_x: false
      use_velocity_scaled_decel_lim_x: false
      use_velocity_scaled_max_speed_x: false
      use_velocity_scaled_min_speed_x: false
      use_velocity_scaled_max_vel_w: false
      use_velocity_scaled_min_vel_w: false
      use_velocity_scaled_acc_lim_w: false
      use_velocity_scaled_decel_lim_w: false
      use_velocity_scaled_max_speed_w: false
      use_velocity_scaled_min_speed_w: false
      use_velocity_scaled_max_vel_v: false
      use_velocity_scaled_min_vel_v: false
      use_velocity_scaled_acc_lim_v: false
      use_velocity_scaled_decel_lim_v: false
      use_velocity_scaled_max_speed_v: false
      use_velocity_scaled_min_speed_v: false
      use_velocity_scaled_max_vel_u: false
      use_velocity_scaled_min_vel_u: false
      use_velocity_scaled_acc_lim_u: false
      use_velocity_scaled_decel_lim_u: false
      use_velocity_scaled_max_speed_u: false
      use_velocity_scaled_min_speed_u: false
      use_velocity_scaled_max_vel_t: false
      use_velocity_scaled_min_vel_t: false
      use_velocity_scaled_acc_lim_t: false
      use_velocity_scaled_decel_lim_t: false
      use_velocity_scaled_max_speed_t: false
      use_velocity_scaled_min_speed_t: false
      use_velocity_scaled_max_vel_s: false
      use_velocity_scaled_min_vel_s: false
      use_velocity_scaled_acc_lim_s: false
      use_velocity_scaled_decel_lim_s: false
      use_velocity_scaled_max_speed_s: false
      use_velocity_scaled_min_speed_s: false
      use_velocity_scaled_max_vel_r: false
      use_velocity_scaled_min_vel_r: false
      use_velocity_scaled_acc_lim_r: false
      use_velocity_scaled_decel_lim_r: false
      use_velocity_scaled_max_speed_r: false
      use_velocity_scaled_min_speed_r: false
      use_velocity_scaled_max_vel_q: false
      use_velocity_scaled_min_vel_q: false
      use_velocity_scaled_acc_lim_q: false
      use_velocity_scaled_decel_lim_q: false
      use_velocity_scaled_max_speed_q: false
      use_velocity_scaled_min_speed_q: false
      use_velocity_scaled_max_vel_p: false
      use_velocity_scaled_min_vel_p: false
      use_velocity_scaled_acc_lim_p: false
      use_velocity_scaled_decel_lim_p: false
      use_velocity_scaled_max_speed_p: false
      use_velocity_scaled_min_speed_p: false
      use_velocity_scaled_max_vel_o: false
      use_velocity_scaled_min_vel_o: false
      use_velocity_scaled_acc_lim_o: false
      use_velocity_scaled_decel_lim_o: false
      use_velocity_scaled_max_speed_o: false
      use_velocity_scaled_min_speed_o: false
      use_velocity_scaled_max_vel_n: false
      use_velocity_scaled_min_vel_n: false
      use_velocity_scaled_acc_lim_n: false
      use_velocity_scaled_decel_lim_n: false
      use_velocity_scaled_max_speed_n: false
      use_velocity_scaled_min_speed_n: false
      use_velocity_scaled_max_vel_m: false
      use_velocity_scaled_min_vel_m: false
      use_velocity_scaled_acc_lim_m: false
      use_velocity_scaled_decel_lim_m: false
      use_velocity_scaled_max_speed_m: false
      use_velocity_scaled_min_speed_m: false
      use_velocity_scaled_max_vel_l: false
      use_velocity_scaled_min_vel_l: false
      use_velocity_scaled_acc_lim_l: false
      use_velocity_scaled_decel_lim_l: false
      use_velocity_scaled_max_speed_l: false
      use_velocity_scaled_min_speed_l: false
      use_velocity_scaled_max_vel_k: false
      use_velocity_scaled_min_vel_k: false
      use_velocity_scaled_acc_lim_k: false
      use_velocity_scaled_decel_lim_k: false
      use_velocity_scaled_max_speed_k: false
      use_velocity_scaled_min_speed_k: false
      use_velocity_scaled_max_vel_j: false
      use_velocity_scaled_min_vel_j: false
      use_velocity_scaled_acc_lim_j: false
      use_velocity_scaled_decel_lim_j: false
      use_velocity_scaled_max_speed_j: false
      use_velocity_scaled_min_speed_j: false
      use_velocity_scaled_max_vel_i: false
      use_velocity_scaled_min_vel_i: false
      use_velocity_scaled_acc_lim_i: false
      use_velocity_scaled_decel_lim_i: false
      use_velocity_scaled_max_speed_i: false
      use_velocity_scaled_min_speed_i: false
      use_velocity_scaled_max_vel_h: false
      use_velocity_scaled_min_vel_h: false
      use_velocity_scaled_acc_lim_h: false
      use_velocity_scaled_decel_lim_h: false
      use_velocity_scaled_max_speed_h: false
      use_velocity_scaled_min_speed_h: false
      use_velocity_scaled_max_vel_g: false
      use_velocity_scaled_min_vel_g: false
      use_velocity_scaled_acc_lim_g: false
      use_velocity_scaled_decel_lim_g: false
      use_velocity_scaled_max_speed_g: false
      use_velocity_scaled_min_speed_g: false
      use_velocity_scaled_max_vel_f: false
      use_velocity_scaled_min_vel_f: false
      use_velocity_scaled_acc_lim_f: false
      use_velocity_scaled_decel_lim_f: false
      use_velocity_scaled_max_speed_f: false
      use_velocity_scaled_min_speed_f: false
      use_velocity_scaled_max_vel_e: false
      use_velocity_scaled_min_vel_e: false
      use_velocity_scaled_acc_lim_e: false
      use_velocity_scaled_decel_lim_e: false
      use_velocity_scaled_max_speed_e: false
      use_velocity_scaled_min_speed_e: false
      use_velocity_scaled_max_vel_d: false
      use_velocity_scaled_min_vel_d: false
      use_velocity_scaled_acc_lim_d: false
      use_velocity_scaled_decel_lim_d: false
      use_velocity_scaled_max_speed_d: false
      use_velocity_scaled_min_speed_d: false
      use_velocity_scaled_max_vel_c: false
      use_velocity_scaled_min_vel_c: false
      use_velocity_scaled_acc_lim_c: false
      use_velocity_scaled_decel_lim_c: false
      use_velocity_scaled_max_speed_c: false
      use_velocity_scaled_min_speed_c: false
      use_velocity_scaled_max_vel_b: false
      use_velocity_scaled_min_vel_b: false
      use_velocity_scaled_acc_lim_b: false
      use_velocity_scaled_decel_lim_b: false
      use_velocity_scaled_max_speed_b: false
      use_velocity_scaled_min_speed_b: false
      use_velocity_scaled_max_vel_a: false
      use_velocity_scaled_min_vel_a: false
      use_velocity_scaled_acc_lim_a: false
      use_velocity_scaled_decel_lim_a: false
      use_velocity_scaled_max_speed_a: false
      use_velocity_scaled_min_speed_a: false
